name: Cypress tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.1  
      - name: Cypress.io
        uses: cypress-io/github-action@v2.9.7
        with:
              build: npm run build
              start: npm start
  messageSlack:
    runs-on: ubuntu-latest
    steps:
    - name: Slack Messenger
      uses: joshmgross/send-slack-message@v1.0.1
      with:
        message: "Testing the shit out"
        slack-token: ${{ secrets.SLACK_BOT_TOKEN }}
        channel: C03CJCMKW1J
        
