name: Cypress tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.1  
      - name: Cypress.io
        uses: cypress-io/github-action@v2.9.7
        with:
              build: npm run build
              start: npm start
  messageSlack:
    runs-on: ubuntu-latest
    steps:
    - name: slack-send
      uses: slackapi/slack-github-action@v1.18.0
      with:
        channel-id: 03CJCMKW1J
        slack-message: "Testing the shit out"
        
