name: Cypress tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.1  
      - name: Cypress.io
        uses: cypress-io/github-action@v2.9.7
        with:
              build: npm run build
              start: npm start
  messageSlack:
    runs-on: ubuntu-latest
    steps:
    - name: Notification Slack
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_CHANNEL: ci
        SLACK_TITLE: Post Title
        SLACK_USERNAME: BotCI
        SLACK_WEBHOOK: ${{ secrets.SLACK_BOT_TOKEN }}
        SLACK_MESSAGE: "Testing has been completed"
